### ISSUE TITLE
Need support for bigint/int unsigned type

### ISSUE THREAD

**Issue by vikas22** [artur-tamazian/avro-schema-generator#3]
Ex: schema
```
| Field                    | Type                         | Null   | Key  | Default  |
| amount               | bigint(20) unsigned | NO   | MUL | NULL    |
```

Library throws 
```
Exception in thread "main" java.lang.IllegalArgumentException: unknown data type: bigint unsigned
	at com.at.avro.config.AvroConfig.lambda$new$2(AvroConfig.java:30)
	at com.at.avro.AvroTypeUtil.getPrimitiveType(AvroTypeUtil.java:97)
	at com.at.avro.AvroTypeUtil.getAvroType(AvroTypeUtil.java:43)
	at com.at.avro.AvroField.<init>(AvroField.java:25)
	at com.at.avro.AvroSchema.<init>(AvroSchema.java:26)
	at com.at.avro.DbSchemaExtractor.get(DbSchemaExtractor.java:93)
	at com.at.avro.DbSchemaExtractor.getForTables(DbSchemaExtractor.java:57)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
```

**Comment by vikas22** [comment]
@artur-tamazian @atfire https://github.com/artur-tamazian/avro-schema-generator/pull/4 please check this

**Comment by artur-tamazian** [comment]
I released a new version with your fix. Thanks for the contribution!

**Comment by vikas22** [comment]
https://github.com/artur-tamazian/avro-schema-generator/pull/5/commits/a0e49dc8984aac06611f47f3fa7c7a2b9dfb6b2f @artur-tamazian needed support for smallint unsigned and mediumint please approve

**Comment by artur-tamazian** [comment]
@vikas22 thank you for another contribution! Version 1.0.2 released
