### ISSUE TITLE
Support for DB names with `-` in name.

### ISSUE THREAD

**Issue by Skad00dle** [artur-tamazian/avro-schema-generator#31]
Hi,
for databases which contain `-` (hyphen) in db name, avro generation fails with following error.

```
Exception in thread "main" java.lang.RuntimeException: schemacrawler.schemacrawler.SchemaCrawlerException: No matching schemas found
	at com.at.avro.DbSchemaExtractor.get(DbSchemaExtractor.java:109)
	at com.at.avro.DbSchemaExtractor.getForTables(DbSchemaExtractor.java:57)
	at com.razorpay.edh.test_avro$.delayedEndpoint$com$razorpay$edh$test_avro$1(test_avro.scala:45)
	at com.razorpay.edh.test_avro$delayedInit$body.apply(test_avro.scala:11)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.razorpay.edh.test_avro$.main(test_avro.scala:11)
	at com.razorpay.edh.test_avro.main(test_avro.scala)
Caused by: schemacrawler.schemacrawler.SchemaCrawlerException: No matching schemas found
	at schemacrawler.crawl.SchemaCrawler.crawlSchemas(SchemaCrawler.java:426)
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:144)
	at schemacrawler.tools.catalogloader.SchemaCrawlerCatalogLoader.loadCatalog(SchemaCrawlerCatalogLoader.java:59)
	at schemacrawler.tools.catalogloader.ChainedCatalogLoader.loadCatalog(ChainedCatalogLoader.java:77)
	at schemacrawler.tools.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:103)
	at schemacrawler.tools.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:85)
	at com.at.avro.DbSchemaExtractor.get(DbSchemaExtractor.java:84)

```

it works perfectly fine with the databases which does not contain `-` in the their name.

if have used following code to reproduce issue
```
.
.
.
val db = "test-delete"
val url = s"jdbc:mysql://${host}:${port}/${db}"
val schemaExtractor = new DbSchemaExtractor(url, user, password)
schemas = schemaExtractor
      .getForTables(avroConfig, db, tables: _*)
      .asScala
      .toList
```
while searching at the issue at https://github.com/schemacrawler/SchemaCrawler
i came across this related issue. https://github.com/schemacrawler/SchemaCrawler/issues/176
if possible please check on how to implement the solution.

Used avro-schema-generator version: 1.0.7
Please do let me know if you need any info or help.

Thanks and regards,
Raj

**Comment by artur-tamazian** [comment]
Thanks for reporting!

I was able to reproduce and fix it in https://github.com/artur-tamazian/avro-schema-generator/pull/32. I've tested it using PostgreSQL but I hope it'll work for MySQL too.

What you should try now is to use `avro-schema-generator v1.0.10` (should be available shortly) and use quoted schema name like this: `val db = "\"test-delete\""`. 

There is a chance that a different type of quote is needed for MySQL - in that case, let me know and we'll try to figure something out.

**Comment by Skad00dle** [comment]
Hey @artur-tamazian.
first of all thank you the fix on the bug.


i tried escaping `-` with following ways with mysql 8 but it didnt work.
- "\"test-db\"".  (was able to get table info from schemaCrawler but was dropped in [this](https://github.com/artur-tamazian/avro-schema-generator/blob/d23f256796bc9b77fc5cde26c1596411d78a13bc/src/main/java/com/at/avro/DbSchemaExtractor.java#L100) step)
-  "`test-db`" (failed with " No matching schemas found" since schemaCrawler did not return any matching schema for this )
- ".test-db." (ran successfully but did not generate any schema since schemaCrawler did not return any matching schema for this )

code to reproduce
```
val db = "test-db"  
val escaped_db = "\"test-db\""
val url = s"jdbc:mysql://${host}:${port}/${db}"
val schemaExtractor = new DbSchemaExtractor(url, user, password)
schemas = schemaExtractor
      .getForTables(avroConfig, escaped_db, tables: _*)
      .asScala
      .toList
```

Avro schema generator version: v1.0.10
Mysql version: 8

please help me find the solution for this.
Regards
Raj

**Comment by Skad00dle** [comment]
@artur-tamazian please help on this issue.

**Comment by artur-tamazian** [comment]
Hey Raj! Sorry, I've missed your previous messages.

In the first case above did you use `""test-db""` or did you use it with slashes like `"\"test-db"\"`? When it was dropped [here](https://github.com/artur-tamazian/avro-schema-generator/blob/d23f256796bc9b77fc5cde26c1596411d78a13bc/src/main/java/com/at/avro/DbSchemaExtractor.java#L100) what were the values of 
- `schema.getName()`
- Identifiers.STANDARD.quoteName(schema.getName()))
- dbSchemaName?

Knowing these values might help to understand what's happening. 

In general though it would be nice if you were able to fork this project and add a test that reproduces this. We can try to figure it out without it but this is usually the best way to fix bugs: write test -> reproduce -> fix -> verify.
